version: '2'

services:
  mongo:
    image: "mongo:3.0"
  rabbit:
    image: "rabbitmq:3"
  scheduler:
    build: 
      context: https://github.com/webautotester/wat.git
      dockerfile: ./scheduler/Dockerfile
    image: "xblanc/wat_scheduler"
    depends_on:
      - "rabbit"
      - "mongo"
  api:
    build: 
      context: https://github.com/webautotester/wat.git
      dockerfile: ./api/Dockerfile
    image: "xblanc/wat_api"
    environment:
      NODE_ENV: 'PROD'
    env_file:
      - /etc/wat/auth.env
    depends_on:
      - "rabbit"
      - "mongo"
  front:
    build: 
      context: https://github.com/webautotester/wat.git
      dockerfile: ./front/DockerfileProd
    image: "xblanc/wat_front"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - screens:/var/www/public/img/screen
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - "api"
  player1:
    build: 
      context: https://github.com/webautotester/player.git
      dockerfile: ./player/Dockerfile
    image: "xblanc/wat_player"
    volumes:
      - screens:/tmp/run/screen
    depends_on:
      - "rabbit"
      - "mongo"
  player2:
    build: 
      context: https://github.com/webautotester/player.git
      dockerfile: ./player/Dockerfile
    image: "xblanc/wat_player"
    volumes:
      - screens:/tmp/run/screen
    depends_on:
      - "rabbit"
      - "mongo"

volumes:
  screens:
